general.import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
opacity = 0.85

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
style = "Regular"
